### ISSUE TITLE
Could not denormalize object of type RouteCollection

### ISSUE THREAD

**Issue by hmillet** [FriendsOfSymfony/FOSJsRoutingBundle#270] opened 2016-12-09 12:09 UTC
Hi,

Trying to use the Pre-release - 2.0.0-alpha1 with Symfony 3.2, I get the following exception 

> Could not denormalize object of type Symfony\Component\Routing\RouteCollection, no supporting normalizer found

when I call 

> /js/routing?callback=fos.Router.setData

I know, this is an alpha...

Does anyone know a quick workaround, or should I only have to be patient until next release ?

Will you consider upgrading this bundle in order it works with sf 3 ?

Thanks for your answer

**Comment by stof** [comment] 2016-12-09 16:25
Can you give the stack trace of the exception too ?

**Comment by hmillet** [comment] 2016-12-09 16:39
Here it is.

Now, I can be much more precise :
* It only fails when no route are exposed (so in fact this issue is not really critical ...)
* when I clear the symfony cache, it works... once


```
    Symfony\Component\Serializer\Exception\UnexpectedValueException: Could not denormalize object of type Symfony\Component\Routing\RouteCollection, no supporting normalizer found.
    at n/a
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php line 267

    at Symfony\Component\Serializer\Serializer->denormalizeObject(array(), 'Symfony\\Component\\Routing\\RouteCollection', 'json', array())
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php line 174

    at Symfony\Component\Serializer\Serializer->denormalize(array(), 'Symfony\\Component\\Routing\\RouteCollection', 'json', array())
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/vendor/symfony/symfony/src/Symfony/Component/Serializer/Serializer.php line 132

    at Symfony\Component\Serializer\Serializer->deserialize('[]', 'Symfony\\Component\\Routing\\RouteCollection', 'json')
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/vendor/friendsofsymfony/jsrouting-bundle/Controller/Controller.php line 91

    at FOS\JsRoutingBundle\Controller\Controller->indexAction(object(Request), 'js')
        in  line 

    at call_user_func_array(array(object(Controller), 'indexAction'), array(object(Request), 'js'))
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/var/cache/dev/classes.php line 4898

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/var/cache/dev/classes.php line 4853

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 168

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /home/hmillet/workspaces/wayatech/waya-backup-gui/web/app_dev.php line 32
```

**Comment by stof** [comment] 2016-12-09 16:41
If it only happens when there is no exposed routes, I know what the issue is and how to fix it. Thanks for this additional info.

**Comment by stof** [comment] 2016-12-09 16:42
and regarding clearing the cache, this is logical, as this exception happens when loading the exposed routes from the cache (and so the first request after clearing the cache does not have this issue, as there is no cache to reload yet)

**Comment by tobias-93** [comment] 2017-11-08 21:22
Is this issue still actual?

**Comment by jcrombez** [comment] 2017-11-27 14:00
I just got it with a fresh install so yes.

**Comment by bilalyilmax** [comment] 2017-11-29 11:11
Same error like jcrombez's, Any solution?

**Comment by tobias-93** [comment] 2017-11-29 11:37
I have committed a fix in the master branch, could one of you check if the issue is fixed? If that is the case I'll tag a new release.

**Comment by zquintana** [comment] 2017-12-01 04:38
@tobias-93, I tried your fix on master on a project I'm working on. It doesn't throw an exception, but the routes are empty:

~~~
/**/fos.Router.setData({"base_url":"\/app_dev.php","routes":[],"prefix":"","host":"localhost","scheme":"http"});
~~~

**Comment by zquintana** [comment] 2017-12-01 04:40
Turns out the routes were empty because I forgot the options expose attribute in the route config. Thanks for the fix!

**Comment by tobias-93** [comment] 2017-12-01 05:29
@zquintana thank you for confirming the fix works. The fix is specifically for the case that no routes are exposed, so that would be expected behaviour. Did you also check it worked without exposed routes after building the cache?

**Closed** 2017-12-13 08:29 UTC
